package payloadutilitis;

public class DirectAdmissionPayLoad  {
	
	public static String CreateDirectAdmission() {
		
		
		return "{\r\n"
				+ "    \"id\": \"\",\r\n"
				+ "    \"version\": \"\",\r\n"
				+ "    \"person\": {\r\n"
				+ "        \"id\": \"\",\r\n"
				+ "        \"version\": \"\",\r\n"
				+ "        \"isEmployeeOfOrganization\": false,\r\n"
				+ "        \"salutation\": {\r\n"
				+ "            \"id\": 1\r\n"
				+ "        },\r\n"
				+ "        \"firstName\": \"API\",\r\n"
				+ "        \"middleName\": \"\",\r\n"
				+ "        \"lastName\": \"Stu 1\",\r\n"
				+ "        \"shortName\": \"API Stu 1\",\r\n"
				+ "        \"initials\": \"\",\r\n"
				+ "        \"printName\": \"API Stu 1\",\r\n"
				+ "        \"genderCSM\": {\r\n"
				+ "            \"id\": 1\r\n"
				+ "        },\r\n"
				+ "        \"firstNameOtherLanguage\": \"\",\r\n"
				+ "        \"middleNameOtherLanguage\": \"\",\r\n"
				+ "        \"lastNameOtherLanguage\": \"\",\r\n"
				+ "        \"shortNameOtherLanguage\": \"\",\r\n"
				+ "        \"printNameOtherLanguage\": \"\",\r\n"
				+ "        \"birthDate\": \"2025-05-13\",\r\n"
				+ "        \"birthPlace\": \"\",\r\n"
				+ "        \"birthPlaceOtherLanguage\": \"\",\r\n"
				+ "        \"country\": {\r\n"
				+ "            \"id\": 1\r\n"
				+ "        },\r\n"
				+ "        \"nationality\": {\r\n"
				+ "            \"id\": 108\r\n"
				+ "        },\r\n"
				+ "        \"idtype\": null,\r\n"
				+ "        \"idNumberSecond\": \"\",\r\n"
				+ "        \"nationalID\": \"\",\r\n"
				+ "        \"identityExpiryDate\": \"\",\r\n"
				+ "        \"ifOtherPleaseGiveDetails\": \"\",\r\n"
				+ "        \"leadChannel\": \"\",\r\n"
				+ "        \"agencysName\": \"\",\r\n"
				+ "        \"leadOwner\": \"\",\r\n"
				+ "        \"unconditionalOfferSentDate\": \"\",\r\n"
				+ "        \"specifyOther\": \"\",\r\n"
				+ "        \"entryRoute\": \"\",\r\n"
				+ "        \"pleaseChooseAfterReadingInfo\": \"\",\r\n"
				+ "        \"dateTimeOfInterview\": \"\",\r\n"
				+ "        \"englishProficiency\": \"\",\r\n"
				+ "        \"motivation\": \"\",\r\n"
				+ "        \"commentsByInterviewer\": \"\",\r\n"
				+ "        \"decisionByInterviewer\": \"\",\r\n"
				+ "        \"isLearnerSACitizen\": true,\r\n"
				+ "        \"isWheelChairRequired\": false,\r\n"
				+ "        \"diplomaticStatus\": false,\r\n"
				+ "        \"temporaryStudy\": false,\r\n"
				+ "        \"workCriticalSkills\": false,\r\n"
				+ "        \"postgraduateNonResidentialStudent\": false,\r\n"
				+ "        \"isTertiaryInstitution\": false,\r\n"
				+ "        \"isEnrolledTertiaryInstitute\": false,\r\n"
				+ "        \"isAutomateExchange\": false,\r\n"
				+ "        \"academicBankCredits\": \"\",\r\n"
				+ "        \"coaStudent\": \"\",\r\n"
				+ "        \"naadStudent\": \"\",\r\n"
				+ "        \"consentedCommunicationChannel\": [],\r\n"
				+ "        \"consentStatementAccepted\": false,\r\n"
				+ "        \"phoneCountryCode\": \"+44\",\r\n"
				+ "        \"phoneAreaCode\": \"\",\r\n"
				+ "        \"phoneNo\": \"\",\r\n"
				+ "        \"mobileCountryCode\": \"+91\",\r\n"
				+ "        \"mobileNumber\": \"9874563214\",\r\n"
				+ "        \"alternateMobileCountryCode\": \"+44\",\r\n"
				+ "        \"alternateMobileNo\": \"\",\r\n"
				+ "        \"emailId\": \"test^@gmail.com\",\r\n"
				+ "        \"alternateEmailId\": \"\",\r\n"
				+ "        \"emergencyFirstName\": \"\",\r\n"
				+ "        \"emergencyLastName\": \"\",\r\n"
				+ "        \"emergencyMobileCountryCode\": \"\",\r\n"
				+ "        \"emergencyMobileNumber\": \"\",\r\n"
				+ "        \"comments\": \"\",\r\n"
				+ "        \"externalSysRefOne\": \"\",\r\n"
				+ "        \"externalSysRefTwo\": \"\",\r\n"
				+ "        \"externalSysRefThree\": \"\",\r\n"
				+ "        \"bloodGroup\": null,\r\n"
				+ "        \"maritalStatus\": null,\r\n"
				+ "        \"category\": \"\",\r\n"
				+ "        \"postNumber\": \"\",\r\n"
				+ "        \"personalIncome\": \"\",\r\n"
				+ "        \"accountingKey\": \"\",\r\n"
				+ "        \"hpcsaRegNo\": \"\",\r\n"
				+ "        \"whetherCompanySponsored\": false,\r\n"
				+ "        \"applicantSchoolPriority\": null,\r\n"
				+ "        \"haveYouStudiedAtUWC\": false,\r\n"
				+ "        \"studentNoAtUWC\": \"\",\r\n"
				+ "        \"areYouRegisteredAtOtherSAU\": false,\r\n"
				+ "        \"studentNoAtOtherSAU\": \"\",\r\n"
				+ "        \"isRegistrationContractCondition\": false,\r\n"
				+ "        \"isRegistrationContract\": false,\r\n"
				+ "        \"customData\": [\r\n"
				+ "            {\r\n"
				+ "                \"cf18\": \"\",\r\n"
				+ "                \"id\": \"\",\r\n"
				+ "                \"version\": \"\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"applicantPersonDisability\": [],\r\n"
				+ "        \"applicantPersonEducationInterventions\": [],\r\n"
				+ "        \"status\": \"ACTIVE\",\r\n"
				+ "        \"bankDetail\": null,\r\n"
				+ "        \"applicantPhysicalCharacteristics\": null,\r\n"
				+ "        \"languageCompetency\": [\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"\"\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    },\r\n"
				+ "    \"code\": \"\",\r\n"
				+ "    \"applicationFormId\": \"\",\r\n"
				+ "    \"currentStatus\": \"DIRECT_ADMISSION\",\r\n"
				+ "    \"existingStudentId\": \"\",\r\n"
				+ "    \"enquiryStudentDetailId\": \"\",\r\n"
				+ "    \"reservationCategory\": null,\r\n"
				+ "    \"familyIncome\": \"\",\r\n"
				+ "    \"saleRefType\": \"\",\r\n"
				+ "    \"saleRefId\": \"\",\r\n"
				+ "    \"submissionDate\": \"\",\r\n"
				+ "    \"applicationEnquiryMultipleMode\": []\r\n"
				+ "}";
	}

}
