package payloadutilitis;

import StringUtilities.StringUtils;
import pojo.programpojo;
import variableutility.GlobalVariable;

public class PayloadProgramModule extends programpojo{
	
	public static String createProgramPayload() {
		
		setProgramcode(StringUtils.randomPrgCodeGenerator());
	    setProgramename(StringUtils.randomProgramNamegenerator());
		
		
		return "{\r\n"
				+ "  \"version\": \"\",\r\n"
				+ "  \"programCode\": \""+getProgramcode()+"\",\r\n"
				+ "  \"programName\": \""+getProgramename()+"\",\r\n"
				+ "  \"academyLocation\": {\r\n"
				+ "    \"id\": 1\r\n"
				+ "  },\r\n"
				+ "  \"accreditationFromDate\": \"\",\r\n"
				+ "  \"accreditationProgramAccreditation\": \"\",\r\n"
				+ "  \"accreditationTillDate\": \"\",\r\n"
				+ "  \"admissionRequirements\": \"<html><head><title></title></head><body></body></html>\",\r\n"
				+ "  \"bursaryInformation\": \"<html><head><title></title></head><body></body></html>\",\r\n"
				+ "  \"customData\": [\r\n"
				+ "    {\r\n"
				+ "      \"cf16\": \"false\",\r\n"
				+ "      \"id\": \"\",\r\n"
				+ "      \"version\": \"\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"departmentByProgramDepartmentId\": {\r\n"
				+ "    \"id\": 7,\r\n"
				+ "    \"value\": \"GIHE UK\"\r\n"
				+ "  },\r\n"
				+ "  \"duration\": \"\",\r\n"
				+ "  \"educationDepartmentProgramCode\": \"\",\r\n"
				+ "  \"educationDepartmentRegistrationDate\": \"\",\r\n"
				+ "  \"fieldOfStudyLanguageTwo\": \"\",\r\n"
				+ "  \"fieldOfStudyOtherLanguage\": \"\",\r\n"
				+ "  \"graduationCertificateToBePrint\": \"\",\r\n"
				+ "  \"isHtmlContent\": true,\r\n"
				+ "  \"isLongDistanceProgram\": true,\r\n"
				+ "  \"isPeriodTransitionApplicable\": false,\r\n"
				+ "  \"isSingleCourseProgram\": true,\r\n"
				+ "  \"presentationLanguageId\": \"\",\r\n"
				+ "  \"printNameInOtherLanguage1\": \"\",\r\n"
				+ "  \"printNameInOtherLanguage2\": \"\",\r\n"
				+ "  \"programAreaOfInterests\": [],\r\n"
				+ "  \"programCategory\": {\r\n"
				+ "    \"id\": 2,\r\n"
				+ "    \"value\": \"BBA Programs\"\r\n"
				+ "  },\r\n"
				+ "  \"programCourseGroupMapping\": [],\r\n"
				+ "  \"programDesignator\": \"\",\r\n"
				+ "  \"programDocuments\": [],\r\n"
				+ "  \"programGroup\": {\r\n"
				+ "    \"id\": 4,\r\n"
				+ "    \"value\": \"Undergraduate\"\r\n"
				+ "  },\r\n"
				+ "  \"programMarkGrade\": \"G\",\r\n"
				+ "  \"programNameLanguageOne\": \"\",\r\n"
				+ "  \"programNameLanguageThree\": \"\",\r\n"
				+ "  \"programNameLanguageTwo\": \"\",\r\n"
				+ "  \"programNameToBePrint\": \""+getProgramename()+"\",\r\n"
				+ "  \"programNameToBePrintLanguageOne\": \"\",\r\n"
				+ "  \"programNameToBePrintLanguageThree\": \"\",\r\n"
				+ "  \"programNameToBePrintLanguageTwo\": \"\",\r\n"
				+ "  \"programQualifier\": \"\",\r\n"
				+ "  \"programRegistrationId\": \"\",\r\n"
				+ "  \"programSecondQualifier\": \"\",\r\n"
				+ "  \"programSequence\": \"\",\r\n"
				+ "  \"programShortName\": \"BTech COmputersceince\",\r\n"
				+ "  \"programShortNameLanguageOne\": \"\",\r\n"
				+ "  \"programShortNameLanguageThree\": \"\",\r\n"
				+ "  \"programShortNameLanguageTwo\": \"\",\r\n"
				+ "  \"programSubMerchantId\": \"\",\r\n"
				+ "  \"publishInCatalogue\": false,\r\n"
				+ "  \"remark\": \"\",\r\n"
				+ "  \"saqaId\": \"45999\",\r\n"
				+ "  \"selectionCriteria\": \"<html><head><title></title></head><body></body></html>\",\r\n"
				+ "  \"status\": \"C\",\r\n"
				+ "  \"user\": {\r\n"
				+ "    \"id\": 1,\r\n"
				+ "    \"value\": \"SYSADMIN / SystXm XdmXnXstrXtXr\",\r\n"
				+ "    \"code\": null\r\n"
				+ "  },\r\n"
				+ "  \"videoURL\": \"\",\r\n"
				+ "  \"whetherAccreditation\": false,\r\n"
				+ "  \"whetherCreateNewAdmission\": true,\r\n"
				+ "  \"whetherSucceedingProgram\": false\r\n"
				+ "}\r\n"
				+ "";		
	}
	
	
public static String createProgramBatchPayload() {
		
		return "{\r\n"
				+ "  \"name\": \"\",\r\n"
				+ "  \"seatCapacity\": \"100\",\r\n"
				+ "  \"startDate\": \"2025-05-13\",\r\n"
				+ "  \"tillDate\": \"2025-09-31\",\r\n"
				+ "  \"maxPeriod\": \"3\",\r\n"
				+ "  \"additionalRequirementDetails\": \"\",\r\n"
				+ "  \"ageVerificationDate\": null,\r\n"
				+ "  \"allowMultipleLastPeriods\": false,\r\n"
				+ "  \"batchAwardTypes\": [],\r\n"
				+ "  \"batchOfSucceedingProgram\": \"\",\r\n"
				+ "  \"batchPartTime\": false,\r\n"
				+ "  \"batchResultStatus\": [],\r\n"
				+ "  \"batchSpecializations\": [],\r\n"
				+ "  \"batchStudentClassifications\": [],\r\n"
				+ "  \"batchSubHoldCategory\": [],\r\n"
				+ "  \"calendar\": {\r\n"
				+ "    \"id\": 3,\r\n"
				+ "    \"value\": \"Sommet Academic Cal\"\r\n"
				+ "  },\r\n"
				+ "  \"cgpaRequired\": \"0\",\r\n"
				+ "  \"completionTime\": \"\",\r\n"
				+ "  \"customData\": [],\r\n"
				+ "  \"documents\": [],\r\n"
				+ "  \"eligibilityCriteria\": \"\",\r\n"
				+ "  \"enquiryEnable\": true,\r\n"
				+ "  \"estimatedFees\": \"\",\r\n"
				+ "  \"faq\": \"\",\r\n"
				+ "  \"hasAdditionalRequirement\": false,\r\n"
				+ "  \"intakeYear\": {\r\n"
				+ "    \"id\": 11\r\n"
				+ "  },\r\n"
				+ "  \"isAdvanceConfig\": false,\r\n"
				+ "  \"isEquivalenceCheck\": false,\r\n"
				+ "  \"isFeeApplicable\": false,\r\n"
				+ "  \"isIncludeRepeatedCoursesInCGPA\": false,\r\n"
				+ "  \"isRetentionApplicable\": false,\r\n"
				+ "  \"isTransferCreditFromStudentPortalId\": false,\r\n"
				+ "  \"maxCompulsoryCourses\": \"1\",\r\n"
				+ "  \"maxOptionalCourses\": \"1\",\r\n"
				+ "  \"maxProgramCourses\": \"1\",\r\n"
				+ "  \"maxProgramCredits\": \"1000\",\r\n"
				+ "  \"minCompulsoryCourses\": \"1\",\r\n"
				+ "  \"minOptionalCourses\": \"1\",\r\n"
				+ "  \"minPeriod\": \"1\",\r\n"
				+ "  \"minProgramCourses\": \"1\",\r\n"
				+ "  \"minProgramCredits\": \"0\",\r\n"
				+ "  \"minimumCPA\": \"\",\r\n"
				+ "  \"placementProcessRequired\": \"true\",\r\n"
				+ "  \"printName\": \""+StringUtils.randomBatchGenerator()+"\",\r\n"
				+ "  \"programBatchPrefix\": \"\",\r\n"
				+ "  \"programBatchSeq\": \"1\",\r\n"
				+ "  \"programId\": \""+getProgramidreceived()+"\",\r\n"
				+ "  \"programMaxAge\": 0,\r\n"
				+ "  \"programMinAge\": 0,\r\n"
				+ "  \"programPeriodType\": {\r\n"
				+ "    \"id\": 2,\r\n"
				+ "    \"value\": \"Semester\"\r\n"
				+ "  },\r\n"
				+ "  \"publishInCatalogue\": false,\r\n"
				+ "  \"retainBatch\": \"\",\r\n"
				+ "  \"roundingCount\": \"2\",\r\n"
				+ "  \"roundingMode\": \"HALF_UP\",\r\n"
				+ "  \"sgpaCgpaCalculationRule\": \"Generic Rule\",\r\n"
				+ "  \"specializationPossible\": true,\r\n"
				+ "  \"version\": \"\"\r\n"
				+ "}";		
	}


public static String createSeatPayload() {
	return "{\r\n"
			+ "  \"batchId\": "+getBatchidreceived()+",\r\n"
			+ "  \"retainSeatConfig\": null,\r\n"
			+ "  \"seatCapacity\": \"100\",\r\n"
			+ "  \"seatType\": {\r\n"
			+ "    \"id\": 6,\r\n"
			+ "    \"value\": \"General\"\r\n"
			+ "  },\r\n"
			+ "  \"seatsFilled\": 0,\r\n"
			+ "  \"succeedingSeatConfig\": null,\r\n"
			+ "  \"version\": \"\",\r\n"
			+ "  \"whetherEnableEnquiry\": true\r\n"
			+ "}\r\n"
			+ "";
}

}
